# Generated by Django 3.2.13 on 2022-06-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customer_fix_tp_report_fix_tr_report_prproduct_tproduct_trproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_id', models.CharField(max_length=256)),
                ('product_id', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=256)),
                ('product_num', models.CharField(max_length=256)),
                ('line_num', models.CharField(max_length=256)),
                ('product_price', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='prproduct',
            name='pr_product_cost',
            field=models.CharField(default='100', max_length=256),
        ),
        migrations.AddField(
            model_name='tproduct',
            name='tp_product_cost',
            field=models.CharField(default='100', max_length=256),
        ),
        migrations.AddField(
            model_name='trproduct',
            name='tr_product_cost',
            field=models.CharField(default='100', max_length=256),
        ),
    ]
