# Generated by Django 3.2.13 on 2022-06-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20220627_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_product',
        ),
    ]
