# Generated by Django 3.2.13 on 2022-07-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_send_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tr_order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=256)),
                ('delivery_note', models.CharField(max_length=256)),
                ('delivery_term', models.CharField(max_length=256)),
                ('custormer', models.CharField(max_length=256)),
                ('issue_date', models.DateField(max_length=6)),
                ('due_date', models.DateField(max_length=6)),
                ('invoice_number', models.CharField(max_length=256)),
                ('GST', models.FloatField(default=0.1)),
            ],
        ),
    ]
