# Generated by Django 3.2.13 on 2022-07-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_tr_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='trproduct',
            name='tr_order_list_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.tr_order_list'),
        ),
    ]
