# Generated by Django 3.2.13 on 2022-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_trproduct_tr_order_list_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prproduct',
            name='pr_product_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tproduct',
            name='tp_product_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trproduct',
            name='tr_product_num',
            field=models.IntegerField(),
        ),
    ]
